services:
  db:
    image: mysql:8.4
    container_name: db_mysql_taller_de_programacion
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_ecom_stock
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build:
     context: .
     dockerfile: Dockerfile
    container_name: web_django_taller_de_programacion
    working_dir: /opt/back_end/mi_proyecto/
    #command: >
      /bin/sh -c "/opt/back_end/mi_proyecto/wait-for-it.sh db:3306 -- python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    #healthcheck:
     # test: /bin/sh -c "cd /opt/back_end && chmod +x healthcheck.sh && ./healthcheck.sh"
    volumes:
      - type: bind
        source: .
        target: /opt/back_end/
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=db_ecom_stock

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
